name: guard_class
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth_platform_interface: ^1.1.8
  string_validator: ^0.1.4
  asuka:
    git:
      url: https://github.com/Flutterando/asuka.git
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  dartz: ^0.9.1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^1.3.1
  equatable: ^1.2.2
  connectivity: ^0.4.9
  google_sign_in: ^4.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  modular_codegen: ^1.0.0
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts:
    coverage: flutter test --coverage & remove_from_coverage -f coverage/lcov.info -r .g.dart$
    mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
    mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs