// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
import 'package:dart_json_mapper/dart_json_mapper.dart' show JsonMapper, JsonMapperAdapter, typeOf;

// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:guard_class/app/modules/air_conditioner/infra/models/air_conditioner_configuration_model.dart'
    as prefix1;
import 'package:guard_class/app/modules/air_conditioner/infra/models/air_conditioner_item_model.dart'
    as prefix3;
import 'package:guard_class/app/modules/air_conditioner/infra/models/air_conditioner_log_model.dart'
    as prefix2;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'AirConditionerConfigurationModel',
            r'.AirConditionerConfigurationModel',
            7,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 3, 4, 20],
            const <int>[21, 22, 23, 24, 25, 15, 16, 17, 18, 19],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) => ({id, offset, setpoint, isOn, useRemote}) => b
                  ? prefix1.AirConditionerConfigurationModel(
                      id: id,
                      isOn: isOn,
                      offset: offset,
                      setpoint: setpoint,
                      useRemote: useRemote)
                  : null
            },
            -1,
            0,
            const <int>[],
            const [prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'AirConditionerLogModel',
            r'.AirConditionerLogModel',
            7,
            1,
            const prefix0.JsonSerializable(),
            const <int>[5, 6, 7, 8, 9, 10, 11, 12, 35],
            const <int>[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) => (
                      {offset,
                      setpoint,
                      isOn,
                      useRemote,
                      localTemperature,
                      remoteTemperature,
                      relayStatus,
                      createdAt}) =>
                  b
                      ? prefix2.AirConditionerLogModel(
                          createdAt: createdAt,
                          isOn: isOn,
                          localTemperature: localTemperature,
                          offset: offset,
                          relayStatus: relayStatus,
                          remoteTemperature: remoteTemperature,
                          setpoint: setpoint,
                          useRemote: useRemote)
                      : null
            },
            -1,
            1,
            const <int>[],
            const [prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'AirConditionerItemModel',
            r'.AirConditionerItemModel',
            7,
            2,
            const prefix0.JsonSerializable(),
            const <int>[13, 14, 39],
            const <int>[21, 22, 23, 24, 25, 36, 37, 38],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) => ({configuration, lastLog}) => b
                  ? prefix3.AirConditionerItemModel(
                      configuration: configuration, lastLog: lastLog)
                  : null
            },
            -1,
            2,
            const <int>[],
            const [prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'id', 33797, 0, const prefix0.JsonSerializable(),
            -1, 3, 3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'offset',
            33797,
            0,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4, const <int>[], const []),
        r.VariableMirrorImpl(
            r'setpoint',
            33797,
            0,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5, const <int>[], const []),
        r.VariableMirrorImpl(
            r'isOn',
            33797,
            0,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'useRemote',
            33797,
            0,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'offset',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4, const <int>[], const []),
        r.VariableMirrorImpl(
            r'setpoint',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5, const <int>[], const []),
        r.VariableMirrorImpl(
            r'isOn',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'useRemote',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'localTemperature',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4, const <int>[], const []),
        r.VariableMirrorImpl(
            r'remoteTemperature',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5, const <int>[], const []),
        r.VariableMirrorImpl(
            r'relayStatus',
            33797,
            1,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'createdAt',
            32773,
            1,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3, const <int>[], const []),
        r.VariableMirrorImpl(r'configuration', 33797, 2,
            const prefix0.JsonSerializable(), 0, 0, 0, const <int>[], const []),
        r.VariableMirrorImpl(r'lastLog', 32773, 2,
            const prefix0.JsonSerializable(), 1, 1, 1, const <int>[], const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 15),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 16),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 2, 17),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 3, 18),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 4, 19),
        r.MethodMirrorImpl(
            r'',
            0,
            0,
            -1,
            0,
            0,
            const <int>[],
            const <int>[0, 1, 2, 3, 4],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 6, 6, const <int>[],
            const <int>[5], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 3, 3, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            null,
            null,
            null,
            null,
            const <int>[],
            const <int>[6],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            131075,
            null,
            -1,
            8,
            8,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 5, 26),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 6, 27),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 7, 28),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 8, 29),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 9, 30),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 10, 31),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 11, 32),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 12, 33),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 12, 34),
        r.MethodMirrorImpl(
            r'',
            0,
            1,
            -1,
            1,
            1,
            const <int>[],
            const <int>[7, 8, 9, 10, 11, 12, 13, 14],
            const prefix0.JsonSerializable(),
            const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 13, 36),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 14, 37),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 14, 38),
        r.MethodMirrorImpl(r'', 0, 2, -1, 2, 2, const <int>[],
            const <int>[16, 17], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'id',
            45062,
            20,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #id),
        r.ParameterMirrorImpl(
            r'offset',
            45062,
            20,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            #offset),
        r.ParameterMirrorImpl(
            r'setpoint',
            45062,
            20,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            #setpoint),
        r.ParameterMirrorImpl(
            r'isOn',
            45062,
            20,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            #isOn),
        r.ParameterMirrorImpl(
            r'useRemote',
            45062,
            20,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            #useRemote),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            21,
            const prefix0.JsonSerializable(),
            -1,
            9,
            9,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            23,
            const prefix0.JsonSerializable(),
            -1,
            10,
            10,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'offset',
            45062,
            35,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            #offset),
        r.ParameterMirrorImpl(
            r'setpoint',
            45062,
            35,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            #setpoint),
        r.ParameterMirrorImpl(
            r'isOn',
            45062,
            35,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            #isOn),
        r.ParameterMirrorImpl(
            r'useRemote',
            45062,
            35,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            #useRemote),
        r.ParameterMirrorImpl(
            r'localTemperature',
            45062,
            35,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            #localTemperature),
        r.ParameterMirrorImpl(
            r'remoteTemperature',
            45062,
            35,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            #remoteTemperature),
        r.ParameterMirrorImpl(
            r'relayStatus',
            45062,
            35,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            #relayStatus),
        r.ParameterMirrorImpl(
            r'createdAt',
            45062,
            35,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #createdAt),
        r.ParameterMirrorImpl(
            r'_createdAt',
            32870,
            34,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'configuration',
            45062,
            39,
            const prefix0.JsonSerializable(),
            0,
            0,
            0,
            const <int>[],
            const [],
            null,
            #configuration),
        r.ParameterMirrorImpl(
            r'lastLog',
            45062,
            39,
            const prefix0.JsonSerializable(),
            1,
            1,
            1,
            const <int>[],
            const [],
            null,
            #lastLog),
        r.ParameterMirrorImpl(
            r'_lastLog',
            32870,
            38,
            const prefix0.JsonSerializable(),
            1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.AirConditionerConfigurationModel,
        prefix2.AirConditionerLogModel,
        prefix3.AirConditionerItemModel,
        String,
        double,
        num,
        bool,
        int,
        Type,
        Object,
        Invocation
      ],
      3,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'id': (dynamic instance) => instance.id,
        r'offset': (dynamic instance) => instance.offset,
        r'setpoint': (dynamic instance) => instance.setpoint,
        r'isOn': (dynamic instance) => instance.isOn,
        r'useRemote': (dynamic instance) => instance.useRemote,
        r'localTemperature': (dynamic instance) => instance.localTemperature,
        r'remoteTemperature': (dynamic instance) => instance.remoteTemperature,
        r'relayStatus': (dynamic instance) => instance.relayStatus,
        r'createdAt': (dynamic instance) => instance.createdAt,
        r'configuration': (dynamic instance) => instance.configuration,
        r'lastLog': (dynamic instance) => instance.lastLog
      },
      {
        r'createdAt=': (dynamic instance, value) => instance.createdAt = value,
        r'lastLog=': (dynamic instance, value) => instance.lastLog = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void _initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}

final mainAdapter = JsonMapperAdapter(
  title: 'mainAdapter',
  url: 'package:guard_class/main.dart',
  valueDecorators: {

});

JsonMapper initializeJsonMapper({List<JsonMapperAdapter> adapters = const []}) {
  _initializeReflectable();
  [...adapters, mainAdapter].forEach((x) => JsonMapper().useAdapter(x));
  return JsonMapper();
}